version: 0.2

env:
  variables:
    VERSION: "1.0"
    FLASK_APP: "./src/main.py"
    FLASK_DEBUG: "1"
    FLASK_ENV: "test"
    DB_USER: "postgres"
    DB_PASSWORD: "postgres*123"
    DB_HOST: "database-1.cjuqguqw88vk.us-east-1.rds.amazonaws.com"
    DB_PORT: "5432"
    DB_NAME: "postgres"
    SECRET_TOKEN: "token-super-secreto"
    NEW_RELIC_CONFIG_FILE: "./src/newrelic.ini"

phases:
  install:
    runtime-versions:
      python: 3.11.4
    commands:
      - echo "Instalando pipenv y dependencias del proyecto..."
      - pip install --upgrade pip
      - pip install pipenv

  pre_build:
    commands:
      - echo "Iniciando sesión en ECR..."
      - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 619071342021.dkr.ecr.us-east-1.amazonaws.com
      - echo "Configurando variables de entorno..."
      - export FLASK_APP=$FLASK_APP
      - export FLASK_ENV=$FLASK_ENV
      - export FLASK_DEBUG=$FLASK_DEBUG
      - export DB_USER=$DB_USER
      - export DB_PASSWORD=$DB_PASSWORD
      - export DB_HOST=$DB_HOST
      - export DB_PORT=$DB_PORT
      - export DB_NAME=$DB_NAME
      - export SECRET_TOKEN=$SECRET_TOKEN
      - echo "Instalando dependencias del proyecto con pipenv..."
      - pipenv install --dev

  build:
    commands:
      - echo "Iniciando build de la imagen de Docker"
      - echo "Ejecutando pruebas unitarias con pytest..."
      - docker build --platform linux/amd64 -t devops_08 .
      - docker tag devops_08:latest 619071342021.dkr.ecr.us-east-1.amazonaws.com/devops_08:latest

  post_build:
    commands:
      - echo "Se completó el proceso de build"
      - docker push 619071342021.dkr.ecr.us-east-1.amazonaws.com/devops_08:latest
      - echo "Fase de post-construcción completada."
      - echo "Writing Image Definitions file..."
      - printf '[{"name":"devops08-container", "imageUri":"619071342021.dkr.ecr.us-east-1.amazonaws.com/devops_08:latest"}]' > imageDetail.json
      - printf '{"ImageURI":"619071342021.dkr.ecr.us-east-1.amazonaws.com/devops_08:latest"}' > imageDetail.json
      - cat imagedefinitions.json


artifacts:
  files:
    - '**/*'
    - imagedefinitions.json
    - imageDetail.json
  secondary-artifacts:
    DefinitionArtifact:
      files:
        - appspec.json
        - taskdef.json
    ImageArtifact:
      files:
        - imageDetail.json

