version: 0.2

env:
  variables:
    VERSION: "1.0"
    FLASK_APP: "blacklist/src/main.py"
    FLASK_DEBUG: "1"
    FLASK_ENV: "test"
    DB_USER: "postgres"
    DB_PASSWORD: "postgres"
    DB_HOST: "localhost"
    DB_PORT: "5432"
    DB_NAME: "postgres"
    SECRET_TOKEN: "token-super-secreto"

phases:
  install:
    runtime-versions:
      python: 3.8
    commands:
      - echo "Instalando pipenv y dependencias del proyecto..."
      - pip install --upgrade pip
      - pip install pipenv

  pre_build:
    commands:
      - echo "Configurando variables de entorno..."
      - export FLASK_APP=$FLASK_APP
      - export FLASK_ENV=$FLASK_ENV
      - export FLASK_DEBUG=$FLASK_DEBUG
      - export DB_USER=$DB_USER
      - export DB_PASSWORD=$DB_PASSWORD
      - export DB_HOST=$DB_HOST
      - export DB_PORT=$DB_PORT
      - export DB_NAME=$DB_NAME
      - export SECRET_TOKEN=$SECRET_TOKEN
      - echo "Instalando dependencias del proyecto con pipenv..."
      - pipenv install --dev

  build:
    commands:
      - echo "Ejecutando pruebas unitarias con pytest..."
      - pipenv run pytest

  post_build:
    commands:
      - echo "Fase de post-construcción completada."

artifacts:
  files:
    - '**/*'
  discard-paths: yes
